version: "3.9"
   
services:
  db:
    image: postgres
    restart: always
    expose:
      - 5432
    volumes:
      - ./data/db:/var/lib/postgresql/data
    container_name: fastapi_db
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_DB=postgres
      - POSTGRES_HOST=fastapi_db
      
  web:
    build: .
    command: uvicorn app_name.main:app --host 0.0.0.0 --port 80
    restart: always
    ports: 
     - 80:80
    image: web:code
    container_name: fastapi_cnt
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_DB=postgres
      - POSTGRES_HOST=fastapi_db
    depends_on:
      - db